/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosRouteImport } from './routes/pos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'
import { Route as PosHistoryRouteImport } from './routes/pos.history'
import { Route as DepotPosRouteImport } from './routes/depot.pos'
import { Route as BeautyPosRouteImport } from './routes/beauty.pos'

const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PosHistoryRoute = PosHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PosRoute,
} as any)
const DepotPosRoute = DepotPosRouteImport.update({
  id: '/depot/pos',
  path: '/depot/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const BeautyPosRoute = BeautyPosRouteImport.update({
  id: '/beauty/pos',
  path: '/beauty/pos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRouteWithChildren
  '/beauty/pos': typeof BeautyPosRoute
  '/depot/pos': typeof DepotPosRoute
  '/pos/history': typeof PosHistoryRoute
  '/receipt/$id': typeof ReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRouteWithChildren
  '/beauty/pos': typeof BeautyPosRoute
  '/depot/pos': typeof DepotPosRoute
  '/pos/history': typeof PosHistoryRoute
  '/receipt/$id': typeof ReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRouteWithChildren
  '/beauty/pos': typeof BeautyPosRoute
  '/depot/pos': typeof DepotPosRoute
  '/pos/history': typeof PosHistoryRoute
  '/receipt/$id': typeof ReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/pos'
    | '/beauty/pos'
    | '/depot/pos'
    | '/pos/history'
    | '/receipt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/pos'
    | '/beauty/pos'
    | '/depot/pos'
    | '/pos/history'
    | '/receipt/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/pos'
    | '/beauty/pos'
    | '/depot/pos'
    | '/pos/history'
    | '/receipt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRouteWithChildren
  BeautyPosRoute: typeof BeautyPosRoute
  DepotPosRoute: typeof DepotPosRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/history': {
      id: '/pos/history'
      path: '/history'
      fullPath: '/pos/history'
      preLoaderRoute: typeof PosHistoryRouteImport
      parentRoute: typeof PosRoute
    }
    '/depot/pos': {
      id: '/depot/pos'
      path: '/depot/pos'
      fullPath: '/depot/pos'
      preLoaderRoute: typeof DepotPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beauty/pos': {
      id: '/beauty/pos'
      path: '/beauty/pos'
      fullPath: '/beauty/pos'
      preLoaderRoute: typeof BeautyPosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PosRouteChildren {
  PosHistoryRoute: typeof PosHistoryRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosHistoryRoute: PosHistoryRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PosRoute: PosRouteWithChildren,
  BeautyPosRoute: BeautyPosRoute,
  DepotPosRoute: DepotPosRoute,
  ReceiptIdRoute: ReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
